# Generated by Django 6.0 on 2025-12-27 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('maths', 'Maths')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('#3b82f6', 'Blue'), ('#8b5cf6', 'Purple'), ('#ec4899', 'Pink'), ('#10b981', 'Green'), ('#f59e0b', 'Orange')], default='#3b82f6', max_length=7)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('total_videos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='progress.subject')),
            ],
            options={
                'db_table': 'chapters',
                'ordering': ['subject', 'order', 'title'],
                'unique_together': {('subject', 'title')},
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('videos_watched', models.IntegerField(default=0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='progress.chapter')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'video_progress',
                'unique_together': {('student', 'chapter')},
            },
        ),
    ]
